version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local